-- MAMP / local phpMyAdmin import: no database selection required.
-- Creates tables only. Existing records and passwords are preserved.
CREATE DATABASE IF NOT EXISTS `sena_digital_hub`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `sena_digital_hub`;

CREATE TABLE IF NOT EXISTS systems (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 description VARCHAR(255) NOT NULL DEFAULT '',
 url TEXT NULL,
 icon VARCHAR(40) NOT NULL DEFAULT 'apps',
 color VARCHAR(7) NOT NULL DEFAULT '#176b55',
 category VARCHAR(30) NOT NULL DEFAULT 'student',
 sort_order INT NOT NULL DEFAULT 0,
 active TINYINT(1) NOT NULL DEFAULT 1,
 featured TINYINT(1) NOT NULL DEFAULT 0,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS admins (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role VARCHAR(20) NOT NULL DEFAULT 'admin',
 display_name VARCHAR(150) NOT NULL DEFAULT '',
 email VARCHAR(254) NOT NULL DEFAULT '',
 phone VARCHAR(40) NOT NULL DEFAULT '',
 position VARCHAR(150) NOT NULL DEFAULT '',
 bio TEXT NULL,
 avatar_file VARCHAR(40) NULL,
 active TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings (
 setting_key VARCHAR(50) PRIMARY KEY,
 setting_value TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS login_attempts (
 attempt_key VARCHAR(64) PRIMARY KEY,
 failures INT NOT NULL DEFAULT 0,
 started_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_categories (
 system_id INT UNSIGNED NOT NULL,
 category_key VARCHAR(30) NOT NULL,
 PRIMARY KEY(system_id,category_key),
 INDEX category_lookup(category_key,system_id),
 FOREIGN KEY(system_id) REFERENCES systems(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 actor_id INT UNSIGNED NOT NULL,
 action VARCHAR(40) NOT NULL,
 subject VARCHAR(200) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX audit_time(created_at,id),
 INDEX audit_actor(actor_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
