<?php
require dirname(__DIR__).'/app/bootstrap.php';require_admin();require dirname(__DIR__).'/app/admin-layout.php';
try {
 $stats=db()->query("SELECT COUNT(*) total,COALESCE(SUM(active=1 AND url IS NOT NULL AND url<>''),0) ready,COALESCE(SUM(active=0),0) hidden,COALESCE(SUM(url IS NULL OR url=''),0) pending FROM systems")->fetch();
 $recent=db()->query('SELECT id,name,active,updated_at FROM systems ORDER BY updated_at DESC,id DESC LIMIT 6')->fetchAll();
 $users=(int)db()->query('SELECT COUNT(*) FROM admins')->fetchColumn();$ready=management_ready(db());
 $groups=$ready?db()->query('SELECT category_key,COUNT(*) total FROM system_categories GROUP BY category_key')->fetchAll(PDO::FETCH_KEY_PAIR):[];
}catch(Throwable $err){unavailable($err);}
admin_open('dashboard','ภาพรวมศูนย์บริการ','ติดตามความพร้อมของเว็บไซต์และเข้าถึงงานที่ใช้บ่อย');admin_feedback(); ?>
<div class="dashboard-stats"><?php foreach([['total','ระบบทั้งหมด','apps','purple'],['ready','พร้อมใช้งาน','link','green'],['pending','รอเพิ่มลิงก์','clipboard','amber'],['hidden','ซ่อนอยู่','shield-lock','purple']] as [$key,$label,$glyph,$tone]): ?><a class="status-tile status-<?= $tone ?>" href="index.php<?= $key==='pending'?'?status=pending':($key==='hidden'?'?status=hidden':'') ?>"><?= icon($glyph) ?><div><strong><?= number_format($stats[$key]) ?></strong><span><?= $label ?></span></div><?= icon('arrow-right') ?></a><?php endforeach; ?></div>
<section class="workspace-welcome panel"><div><p class="eyebrow dark">ทุกงานในที่เดียว</p><h2>พร้อมจัดการบริการของเสนา</h2><p><?= number_format($users) ?> บัญชีทีมงาน · <?= count(categories()) ?> หมวดหมู่บริการ</p></div><div class="form-actions"><a class="button" href="index.php#editor"><?= icon('plus') ?> เพิ่มระบบใหม่</a><a class="button secondary" href="menus.php">จัดการเมนู</a><a class="button secondary" href="users.php#user-editor">เพิ่มผู้ใช้</a></div></section>
<div class="workspace-columns"><section class="panel"><div class="panel-heading"><h2>ระบบที่อัปเดตล่าสุด</h2><a href="index.php">ดูทั้งหมด</a></div><?php foreach($recent as $s): ?><a class="dashboard-row" href="index.php?edit=<?= (int)$s['id'] ?>#editor"><div><strong><?= e($s['name']) ?></strong><small><?= e($s['updated_at']) ?></small></div><span class="status-badge <?= !$s['active']?'is-hidden':'' ?>"><?= $s['active']?'แสดงอยู่':'ซ่อนแล้ว' ?></span><?= icon('arrow-right') ?></a><?php endforeach; ?><?php if(!$recent): ?><p class="empty-message">ยังไม่มีเว็บไซต์ เพิ่มบริการแรกเพื่อเริ่มใช้งาน</p><?php endif; ?></section><section class="panel"><div class="panel-heading"><h2>หมวดหมู่บริการ</h2><a href="menus.php">จัดการ</a></div><?php foreach(category_definitions() as $category): ?><a class="dashboard-row" href="index.php?category=<?= e($category['key']) ?>"><?= icon($category['icon']) ?><strong><?= e($category['label']) ?></strong><span class="count"><?= (int)($groups[$category['key']] ?? 0) ?></span></a><?php endforeach; ?></section></div>
<?php admin_close();
