<?php
require dirname(__DIR__).'/app/bootstrap.php'; require_admin();
$error=''; $draft=null;
try {
 if ($_SERVER['REQUEST_METHOD']==='POST') {
  check_csrf(); $action=(string)($_POST['action'] ?? '');
  if ($action==='logout') { $_SESSION=[]; session_destroy(); header('Location: login.php'); exit; }
  if ($action==='save') {
   $draft=['id'=>(int)($_POST['id'] ?? 0),'name'=>trim((string)($_POST['name'] ?? '')),'description'=>trim((string)($_POST['description'] ?? '')),'url'=>trim((string)($_POST['url'] ?? '')),'icon'=>(string)($_POST['icon'] ?? ''),'category'=>(string)($_POST['category'] ?? ''),'color'=>(string)($_POST['color'] ?? ''),'sort_order'=>(int)($_POST['sort_order'] ?? 0),'active'=>isset($_POST['active'])?1:0,'featured'=>0];
   if ($draft['name']==='' || mb_strlen($draft['name'])>150 || mb_strlen($draft['description'])>255) $error='กรุณาระบุชื่อไม่เกิน 150 ตัวอักษร และรายละเอียดไม่เกิน 255 ตัวอักษร';
   elseif ($draft['url']!=='' && (!valid_url($draft['url']) || strlen($draft['url'])>2048)) $error='URL ต้องขึ้นต้นด้วย http:// หรือ https:// และยาวไม่เกิน 2,048 ตัวอักษร';
   elseif (!isset(categories()[$draft['category']]) || !in_array($draft['icon'],icons(),true) || !preg_match('/^#[0-9a-fA-F]{6}$/',$draft['color'])) $error='หมวดหมู่ ไอคอน หรือสีไม่ถูกต้อง';
   else {
    $values=[$draft['name'],$draft['description'],$draft['url']?:null,$draft['icon'],$draft['category'],$draft['color'],$draft['sort_order'],$draft['active']];
    if ($draft['id']) { $stmt=db()->prepare('UPDATE systems SET name=?,description=?,url=?,icon=?,category=?,color=?,sort_order=?,active=? WHERE id=?'); $stmt->execute([...$values,$draft['id']]); }
    else { $stmt=db()->prepare('INSERT INTO systems(name,description,url,icon,category,color,sort_order,active) VALUES (?,?,?,?,?,?,?,?)'); $stmt->execute($values); }
   }
  } elseif ($action==='delete') { $stmt=db()->prepare('DELETE FROM systems WHERE id=?'); $stmt->execute([(int)($_POST['id'] ?? 0)]); }
  elseif ($action==='settings') {
   $public=trim((string)($_POST['public_url'] ?? '')); $contact=trim((string)($_POST['contact'] ?? '')); $notice=trim((string)($_POST['notice'] ?? ''));
   if ($public!=='' && (!valid_url($public) || parse_url($public,PHP_URL_SCHEME)!=='https' || strlen($public)>2048 || parse_url($public,PHP_URL_FRAGMENT) || parse_url($public,PHP_URL_QUERY))) $error='กรุณาใช้ URL สาธารณะแบบ https:// โดยไม่มี query หรือ #';
   elseif(mb_strlen($contact)>2000 || mb_strlen($notice)>2000) $error='ข้อความต้องไม่เกิน 2,000 ตัวอักษร';
   else { $stmt=db()->prepare('INSERT INTO settings(setting_key,setting_value) VALUES (?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)'); db()->beginTransaction(); foreach(['public_url'=>$public,'contact'=>$contact,'notice'=>$notice] as $k=>$v) $stmt->execute([$k,$v]); db()->commit(); }
  } elseif ($action==='password') {
   $stmt=db()->prepare('SELECT password_hash FROM admins WHERE id=?'); $stmt->execute([$_SESSION['admin_id']]);
   if (!password_verify((string)($_POST['current_password'] ?? ''),(string)$stmt->fetchColumn())) $error='รหัสผ่านปัจจุบันไม่ถูกต้อง';
   elseif (strlen((string)($_POST['new_password'] ?? ''))<12) $error='รหัสผ่านใหม่ต้องมีอย่างน้อย 12 ตัวอักษร';
   elseif ($_POST['new_password']!==($_POST['confirm_password'] ?? '')) $error='รหัสผ่านใหม่ทั้งสองช่องไม่ตรงกัน';
   else { $stmt=db()->prepare('UPDATE admins SET password_hash=? WHERE id=?'); $stmt->execute([password_hash($_POST['new_password'],PASSWORD_DEFAULT),$_SESSION['admin_id']]); session_regenerate_id(true); }
  } else $error='คำสั่งไม่ถูกต้อง';
  if (!$error) { $_SESSION['flash']='บันทึกเรียบร้อยแล้ว'; header('Location: index.php'.($action==='settings'?'#settings':($action==='password'?'#security':''))); exit; }
 }
 $systems=db()->query('SELECT * FROM systems ORDER BY sort_order,id')->fetchAll(); $settings=settings();
 $edit=$draft ?? ['id'=>0,'name'=>'','description'=>'','url'=>'','icon'=>'apps','category'=>'student','color'=>'#176b55','sort_order'=>count($systems)+1,'active'=>1];
 if (!$draft && isset($_GET['edit'])) { $stmt=db()->prepare('SELECT * FROM systems WHERE id=?'); $stmt->execute([(int)$_GET['edit']]); $found=$stmt->fetch(); if($found) $edit=$found; else $error='ไม่พบระบบที่ต้องการแก้ไข'; }
} catch(Throwable $err) { unavailable($err); }
head('จัดการระบบ', 'admin-ui'); ?>
<header class="header"><div class="container header-inner"><?php brand('../'); ?><span class="admin-label">พื้นที่ผู้ดูแลระบบ</span><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><button class="text-button" name="action" value="logout"><?= icon('logout') ?> ออกจากระบบ</button></form></div></header>
<div class="admin-workspace"><aside class="admin-sidebar"><div class="sidebar-caption">WORKSPACE</div><nav aria-label="Admin navigation"><a href="#catalog"><?= icon('apps') ?><span>ระบบและเว็บไซต์</span></a><a href="#settings"><?= icon('adjustments') ?><span>ตั้งค่าหน้าเว็บ</span></a><a href="#security"><?= icon('shield-lock') ?><span>บัญชีและรหัสผ่าน</span></a></nav><div class="sidebar-note">SENA DIGITAL HUB<br><small>ศูนย์รวมบริการดิจิทัล</small></div></aside><main class="container admin-main" id="catalog"><div class="section-title"><div><p class="eyebrow dark">จัดการศูนย์รวม</p><h1>ระบบและเว็บไซต์</h1><p>เพิ่มบริการของคุณ แล้วให้ผู้ใช้เข้าถึงผ่านหน้า Hub</p></div><a class="button secondary" href="../" target="_blank" rel="noopener">ดูหน้าเว็บไซต์ <?= icon('arrow-up-right') ?></a></div>
<?php if($error): ?><p class="alert error" role="alert"><?= e($error) ?></p><?php endif; ?><?php if(isset($_SESSION['flash'])): ?><p class="alert success" role="status"><?= e($_SESSION['flash']) ?></p><?php unset($_SESSION['flash']); endif; ?>
<div class="admin-status-strip" aria-label="System status"><div class="status-tile status-purple"><?= icon('apps') ?><div><strong><?= count($systems) ?></strong><span>ระบบทั้งหมด</span></div></div><div class="status-tile status-green"><?= icon('link') ?><div><strong><?= count(array_filter($systems, fn($s)=>$s['active'] && $s['url'])) ?></strong><span>พร้อมใช้งาน</span></div></div><div class="status-tile status-amber"><?= icon('clipboard') ?><div><strong><?= count(array_filter($systems, fn($s)=>$s['active'] && !$s['url'])) ?></strong><span>รอเพิ่มลิงก์</span></div></div></div><div class="admin-layout"><section class="panel"><div class="panel-heading"><h2>รายการระบบ <span class="count"><?= count($systems) ?></span></h2><a href="index.php#editor">เพิ่มระบบ</a></div><div class="admin-search"><?= icon('search') ?><label class="sr-only" for="adminSearch">ค้นหารายการระบบ</label><input id="adminSearch" type="search" placeholder="ค้นหาชื่อหรือหมวดหมู่ระบบ..."></div><p id="adminSearchResult" class="search-result" aria-live="polite"></p><div class="admin-list"><?php foreach($systems as $s): ?><div class="admin-row"><span class="system-icon" style="--system-color:<?= e($s['color']) ?>"><?= icon($s['icon']) ?></span><div class="row-info"><strong><?= e($s['name']) ?></strong><small><?= e(categories()[$s['category']]) ?> · ลำดับ <?= e($s['sort_order']) ?> · <?= !$s['active']?'ซ่อนแล้ว':($s['url']?'พร้อมใช้งาน':'รอเพิ่มลิงก์') ?></small></div><a class="edit-link" href="?edit=<?= $s['id'] ?>#editor">แก้ไข</a><form method="post" data-confirm="ลบระบบ <?= e($s['name']) ?>? การลบนี้ไม่กระทบเว็บไซต์เดิม"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="id" value="<?= $s['id'] ?>"><button class="delete-button" name="action" value="delete">ลบ</button></form></div><?php endforeach; ?><?php if(!$systems): ?><p>ยังไม่มีระบบ เพิ่มระบบแรกได้จากฟอร์ม</p><?php endif; ?></div></section>
<section class="panel" id="editor"><div class="editor-symbol"><?= icon($edit['id']?'file-text':'plus') ?></div><h2><?= $edit['id']?'แก้ไขระบบ':'เพิ่มระบบใหม่' ?></h2><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= e($edit['id']) ?>"><label>ชื่อระบบ<input name="name" required maxlength="150" value="<?= e($edit['name']) ?>"></label><label>รายละเอียด<textarea name="description" maxlength="255" rows="2"><?= e($edit['description']) ?></textarea></label><label>URL เว็บไซต์<input name="url" type="url" maxlength="2048" placeholder="https://your-system.com" value="<?= e($edit['url']) ?>"><small>เว้นว่างเพื่อแสดง “รอเพิ่มลิงก์ระบบ”</small></label><label>หมวดหมู่<select name="category"><?php foreach(categories() as $k=>$v): ?><option value="<?= $k ?>" <?= $edit['category']===$k?'selected':'' ?>><?= e($v) ?></option><?php endforeach; ?></select></label><div class="form-grid"><label>ไอคอน<select name="icon"><?php foreach(icons() as $i): ?><option <?= $edit['icon']===$i?'selected':'' ?>><?= e($i) ?></option><?php endforeach; ?></select></label><label>สีไอคอน<input type="color" name="color" value="<?= e($edit['color']) ?>"></label><label>ลำดับ<input type="number" name="sort_order" min="-2147483648" max="2147483647" value="<?= e($edit['sort_order']) ?>"></label></div><label class="checkbox"><input type="checkbox" name="active" <?= $edit['active']?'checked':'' ?>>แสดงบนหน้า Hub</label><div class="form-actions"><button class="button">บันทึกระบบ</button><?php if($edit['id']): ?><a href="index.php#editor">ยกเลิก</a><?php endif; ?></div></form></section></div>
<section class="panel settings-panel" id="settings"><h2>ข้อมูลหน้าเว็บและ LINE Rich Menu</h2><p>ตั้ง URL สาธารณะหลังนำเว็บไซต์ขึ้นโฮสติ้ง เพื่อใช้เชื่อมเมนู LINE</p><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="settings"><label>URL สาธารณะของ Hub<input type="url" name="public_url" value="<?= e($settings['public_url'] ?? '') ?>" placeholder="https://yourdomain.com/portal/"></label><div class="two-columns"><label>ข่าวประชาสัมพันธ์<textarea name="notice" maxlength="2000" rows="3"><?= e($settings['notice'] ?? '') ?></textarea></label><label>ข้อมูลติดต่อ<textarea name="contact" maxlength="2000" rows="3"><?= e($settings['contact'] ?? '') ?></textarea></label></div><button class="button">บันทึกข้อมูลหน้าเว็บ</button></form><div class="line-guide"><h3>URL สำหรับปุ่ม Rich Menu</h3><?php if(!empty($settings['public_url'])): $base=hub_public_url($settings['public_url']); ?><label>รวมระบบ<input readonly value="<?= e($base) ?>" data-copy-input></label><label>นักศึกษา<input readonly value="<?= e($base.'?category=student') ?>" data-copy-input></label><label>ติดต่อเรา<input readonly value="<?= e($base.'?view=contact') ?>" data-copy-input></label><p>คลิกช่องเพื่อเลือก URL แล้วคัดลอกไปตั้งค่า Action แบบ Link / URI ใน LINE OA Manager</p><?php else: ?><p>บันทึก URL สาธารณะก่อน เพื่อแสดงลิงก์สำหรับ Rich Menu</p><?php endif; ?><a href="https://developers.line.biz/en/docs/messaging-api/using-rich-menus/" target="_blank" rel="noopener">อ่านคู่มือจาก LINE Developers ↗</a></div></section>
<section class="panel settings-panel" id="security"><h2>เปลี่ยนรหัสผ่าน Admin</h2><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><input type="hidden" name="action" value="password"><input type="hidden" name="username" autocomplete="username" value="<?= e($_SESSION['admin_username'] ?? '') ?>"><div class="three-columns"><label>รหัสผ่านปัจจุบัน<input name="current_password" type="password" autocomplete="current-password" required></label><label>รหัสผ่านใหม่<input name="new_password" type="password" autocomplete="new-password" minlength="12" required></label><label>ยืนยันรหัสผ่านใหม่<input name="confirm_password" type="password" autocomplete="new-password" minlength="12" required></label></div><button class="button secondary">เปลี่ยนรหัสผ่าน</button></form></section></main></div><footer class="container footer">SENA Digital Hub · ระบบจัดการลิงก์</footer></body></html>
