<?php
require dirname(__DIR__).'/app/bootstrap.php';require_admin();require dirname(__DIR__).'/app/admin-layout.php';
$error='';$data=settings();
if($_SERVER['REQUEST_METHOD']==='POST') {check_csrf();$data=array_merge($data,array_intersect_key($_POST,array_flip(['public_url','contact','notice'])));
    $public=trim((string)($data['public_url'] ?? ''));
    if($public!=='' && (!valid_url($public) || parse_url($public,PHP_URL_SCHEME)!=='https' || strlen($public)>2048 || parse_url($public,PHP_URL_QUERY) || parse_url($public,PHP_URL_FRAGMENT)))$error='URL สาธารณะต้องเป็น https:// โดยไม่มี query หรือ #';
    elseif(mb_strlen((string)$data['contact'])>2000 || mb_strlen((string)$data['notice'])>2000)$error='ข้อความต้องไม่เกิน 2,000 ตัวอักษร';
    else {try{db()->beginTransaction();foreach(['public_url'=>$public,'contact'=>trim($data['contact']),'notice'=>trim($data['notice'])] as $key=>$value)save_setting(db(),$key,$value);audit_change(db(),'settings.update','ข้อมูลหน้าเว็บ');db()->commit();$_SESSION['flash']='บันทึกข้อมูลหน้าเว็บแล้ว';header('Location: settings.php');exit;}catch(Throwable $err){if(db()->inTransaction())db()->rollBack();unavailable($err);}}
}
admin_open('settings','ตั้งค่าหน้าเว็บ','อัปเดตข่าวสาร ข้อมูลติดต่อ และลิงก์เชื่อม LINE');admin_feedback($error); ?>
<div class="workspace-columns"><section class="panel"><h2>ข้อมูลที่แสดงต่อผู้ใช้</h2><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf()) ?>"><label>URL สาธารณะ<input name="public_url" type="url" maxlength="2048" value="<?= e($data['public_url'] ?? '') ?>" placeholder="https://yourdomain.com/sena_hub/"></label><label>ข่าวประชาสัมพันธ์<textarea name="notice" rows="5" maxlength="2000"><?= e($data['notice'] ?? '') ?></textarea></label><label>ข้อมูลติดต่อ<textarea name="contact" rows="5" maxlength="2000"><?= e($data['contact'] ?? '') ?></textarea></label><button class="button">บันทึกข้อมูล</button></form></section><section class="panel"><h2>ลิงก์สำหรับเมนู LINE</h2><p>คลิกช่องเพื่อเลือก URL แล้วคัดลอกไปตั้ง Action แบบ URI</p><?php if(!empty($data['public_url'])):$base=hub_public_url($data['public_url']); ?><label>หน้าเว็บรวม<input readonly data-copy-input value="<?= e($base) ?>"></label><?php foreach(categories() as $key=>$label): ?><label><?= e($label) ?><input readonly data-copy-input value="<?= e($base.'?category='.$key) ?>"></label><?php endforeach; ?><label>ติดต่อเรา<input readonly data-copy-input value="<?= e($base.'?view=contact') ?>"></label><?php else: ?><p class="empty-message">บันทึก URL สาธารณะก่อนเพื่อสร้างลิงก์</p><?php endif; ?><a href="menus.php">จัดการเมนูหน้าเว็บไซต์ <?= icon('arrow-right') ?></a></section></div>
<?php admin_close();
